	SUBROUTINE GET_EXC_FREQ(TYPE,EXC_EN,PHOT_GION,ID,PHOT_ID,NLEV)
	USE PHOT_DATA_MOD
!
	INTEGER ID
	INTEGER PHOT_ID
	INTEGER NLEV
	REAL*8 EXC_EN
	REAL*8 PHOT_GION
	INTEGER TYPE(NLEV)
!
	INTEGER I,TERM
!
	EXC_EN=PD(ID)%EXC_FREQ(PHOT_ID)
	PHOT_GION=PD(ID)%GION(PHOT_ID)
	DO I=1,NLEV
	  TERM=PD(ID)%A_ID(I,PHOT_ID)
	  TYPE(I)=PD(ID)%CROSS_TYPE(TERM,PHOT_ID)
	END DO
!
	RETURN
	END
!
	SUBROUTINE RESET_DO_PHOT(ID,N_PHOT)
	USE PHOT_DATA_MOD
!
	INTEGER ID
	INTEGER N_PHOT
!
	N_PHOT=PD(ID)%NUM_PHOT_ROUTES
	PD(ID)%DO_PHOT(:,:)=.FALSE.
	DO I=1,N_PHOT
	  PD(ID)%DO_PHOT(I,I)=.TRUE.
	END DO
!
	RETURN
	END
