	PROGRAM NEW_SN_MOD
	USE GEN_IN_INTERFACE
	IMPLICIT NONE
!
	REAL*8 FRAC_TIME_STEP
	REAL*8 AGE
!
	INTEGER, PARAMETER :: NMAX=2000
	INTEGER I,J,K
	INTEGER NREC
	INTEGER IOS
!
	CHARACTER(LEN=80) LINE(NMAX)
	CHARACTER(LEN=80) STRING
	CHARACTER(LEN=20) TEMP_STR
!
	OPEN(UNIT=10,FILE='VADAT',STATUS='OLD')
	I=0
	DO WHILE(I .LT. NMAX-1)
	  READ(10,'(A)',IOSTAT=IOS)LINE(I+1)
	  IF(IOS .NE. 0)EXIT
	  I=I+1
	END DO
	NREC=I
	REWIND(UNIT=10)
	WRITE(6,'(A,I4,A)')'Read',NREC,'records from VADAT'
	WRITE(6,*)'Successfully read VADAT file'
!
	FRAC_TIME_STEP=1.1D0
	CALL GEN_IN(FRAC_TIME_STEP,'Fractional time increment -- e.g. 1.10 for a 10% increase')
!
	I=1
	DO WHILE(I .LE. NREC)
!
	  IF(INDEX(LINE(I),'[SN_AGE]') .NE. 0)THEN
	    READ(LINE(I),*)AGE
	    AGE=AGE*FRAC_TIME_STEP
	    WRITE(TEMP_STR,'(F8.4,A)')AGE,'D0'
	    TEMP_STR=ADJUSTL(TEMP_STR)
	    K=INDEX(LINE(I),'  ')
	    LINE(I)=TRIM(TEMP_STR)//LINE(I)(K:)
	  END IF
!
	  IF(INDEX(LINE(I),'[TS_NO]') .NE. 0)THEN
	    READ(LINE(I),*)J
	    J=J+1
	    WRITE(TEMP_STR,'(I3)')J
	    TEMP_STR=ADJUSTL(TEMP_STR)
	    K=INDEX(LINE(I),'  ')
	    LINE(I)=TRIM(TEMP_STR)//LINE(I)(K:)
	  END IF
!
	  IF(INDEX(LINE(I),'[FIX_T]') .NE. 0)THEN
	    STRING=ADJUSTL(STRING)
	    LINE(I)(1:1)='T'
	  END IF
!
	  IF(INDEX(LINE(I),'[LIN_INT]') .NE. 0)THEN
	    STRING=ADJUSTL(STRING)
	    LINE(I)(1:1)='F'
	  END IF
!
	  WRITE(10,'(A)')TRIM(LINE(I))
	  I=I+1
	END DO	
	WRITE(6,'(A,I4,A)')'Written ',I,'records  to VADAT'
!
	STOP
	END	  
