	SUBROUTINE UPDATE_PG_FILENAME(FILENAME)
	IMPLICIT NONE
!
	CHARACTER(LEN=*) FILENAME
!
	INTEGER I,J,K
	INTEGER, PARAMETER :: IZERO=0
	CHARACTER(LEN=6) TMP_STR
!
! Update file name in a systematic way to save typing.
!
	K=INDEX(FILENAME,'_')
	IF(K .NE. 0)K=INDEX(FILENAME(K+1:),'_')+K
	IF(K .NE. 0)THEN
	  J=K+1
	  DO WHILE(FILENAME(J:J) .GE. '0' .AND. FILENAME(J:J) .LE. '9')
	    J=J+1
	  END DO
	  IF(J .NE. K+1)THEN
	    READ(FILENAME(K+1:J-1),*)I
	    I=I+1
	    WRITE(TMP_STR,'(I6)')I
	    TMP_STR=ADJUSTL(TMP_STR)
	    FILENAME=FILENAME(1:K)//TRIM(TMP_STR)//FILENAME(J:)
	  END IF
	END IF
	CALL SET_CASE_LOW(FILENAME,IZERO,IZERO)
	IF(FILENAME .EQ. 'pgplot.ps')FILENAME='pgplot_2.ps'
!
	RETURN
	END
