	SUBROUTINE DETERM_CLUM_POS(DENSITY,XVALS,ND,CLUMP_POS,NCLUMPS)
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER NCLUMPS
	REAL*8 DENSITY(ND)
	REAL*8 XVALS(ND)
	REAL*8 CLUMP_POS(ND)
	INTEGER I,J
!
	J=0
	DO I=2,ND-5
	  IF(DENSITY(I) .GT. DENSITY(I-1) .AND. DENSITY(I) .GT. DENSITY(I+1))THEN
	    J=J+1
	    CLUMP_POS(J)=I
	    WRITE(6,*)J,I
	  END IF
	END DO
	NCLUMPS=J
!
	RETURN
	END
