	SUBROUTINE SMOOTH(SPEC,LTE,VAL,N,ND,OPT,IDENT,FLAG)
	IMPLICIT NONE
	INTEGER N,ND
	REAL*8 SPEC(N,ND),LTE(N,ND),VAL
	CHARACTER*(*) IDENT,OPT
	LOGICAL FLAG
C
C Local variables
C
	INTEGER I,J
	REAL*4 T1,T2,T3,T4
C
	IF( (OPT .NE. IDENT) .AND. (OPT .NE. 'ALL') )RETURN
	IF(LTE(1,ND) .EQ. 0)RETURN
	FLAG=.TRUE.
	DO J=ND-1,1,-1
	  DO I=1,N
	    T1=SPEC(I,J)/LTE(I,J)
	    T2=SPEC(I,J+1)/LTE(I,J+1)
	    IF( 2.0*ABS(T2-T1)/(T2+T1) .GT. VAL)SPEC(I,J)=T2*LTE(I,J)
	  END DO
	END DO
C
	RETURN
	END
