	PROGRAMT TST_WR_COL
	IMPLICIT NONE
C
	INTEGER, PARAMETER :: N=21
	REAL*8 OMEGA(N,N)
	CHARACTER*30 LEVNAME(N)
C
	INTEGER I,J
C
	DO I=1,N
	  DO J=I,N
	    OMEGA(I,J)=(I-1)*n+J
	  END DO
	  WRITE(LEVNAME(I),'(I3.3)')I
	  LEVNAME(I)='A'//levname(I)
	END DO
	LEVNAME(3)='BCDEFGHIJ'//LEVNAME(3)
C
	CALL WR_COL(OMEGA,LEVNAME,N,'SOD',10,' ')
c
	STOP
	END
