C
C
C
	SUBROUTINE WRITSCRAT(NV,DNV,NNV,ND,SCRATREC,LU,DESC)
	IMPLICIT NONE
	INTEGER NNV,ND,SCRATREC,LU,I,J,NT
	REAL*8 NV(NNV,ND),DNV(ND)
	CHARACTER*(*) DESC
	CHARACTER*30 NEWDESC
C
	NEWDESC=DESC
	WRITE(LU,REC=SCRATREC)NNV,NEWDESC
	SCRATREC=SCRATREC+1
	DO I=1,NNV
	  WRITE(LU,REC=SCRATREC)(NV(I,J),J=1,ND)
	  SCRATREC=SCRATREC+1
	END DO
	WRITE(LU,REC=SCRATREC)(DNV(J),J=1,ND)
	SCRATREC=SCRATREC+1
C
	READ(LU,REC=2)NT
	NT=NT+1+NNV
	WRITE(LU,REC=2)NT,ND
C
	RETURN
	END
