	SUBROUTINE DP_ZERO(Z,ND)
	IMPLICIT NONE
!
	INTEGER ND
	REAL*8 Z(ND)
!
! Altered 13-Mar-2013 : WORKSHARE installed
! Altered 28-May-1996 : F90 updated, IMPLCIT NONE installed.
!
!$OMP PARALLEL WORKSHARE
!
	Z=0.0D0
!
!$OMP END PARALLEL WORKSHARE
!
	RETURN
	END
