C
C SUBROUTINE TO PERFORM  VECTOR MULTIPLICATINS. THERE IS TWO POSSIBLE
C MODES :-
C	(1) FA AND ZETA IDENTICAL. FA IS THEN INCREMENTED BY THE 
C		PRODUCT OF RJ AND ESEC. (USED TO INCREMENT FA
C		MATRIX -SEE NOTES)
C	(2) FT AND ZETA DIFFERENT. THIS MAY BE USED TO COMPUTE THE
C		SOURCE FUNCTION.
C
	SUBROUTINE MULTVEC(FA,ZETA,ESEC,RJ,NI)
	IMPLICIT NONE
C
C Altered 24-May-1996 IMPLICIT NONE installed.
C
	INTEGER NI,I
	REAL*8 FA(NI),ESEC(NI),RJ(NI),ZETA(NI)
C
	DO 10 I=1,NI
	  FA(I)=ZETA(I)+ESEC(I)*RJ(I)
10	CONTINUE
C
	RETURN
	END
