	SUBROUTINE RITE_ASC(CI_PRES,CI,DCI,NCI,ND,CIOSCDATE,DESC,LU)
	IMPLICIT NONE
	LOGICAL CI_PRES
	INTEGER NCI,ND,LU
	REAL*8 CI(NCI,ND),DCI(ND)
	CHARACTER*(*) DESC,CIOSCDATE
C
	INTEGER IZERO
	PARAMETER (IZERO=0)
C
	IF(CI_PRES)THEN
	  WRITE(LU,'(1X,A,T30,I5)')'Number of '//DESC//' levels:',NCI
	  WRITE(LU,'(1X,A,T30,A)')DESC//' Oscillator date:',CIOSCDATE
	  WRITE(LU,'(1X,1P8E16.7)')CI
	  WRITE(LU,'(1X,1P8E16.7)')DCI
	ELSE
	  WRITE(LU,'(1X,A,T30,I5)')'Number of '//DESC//' levels:',IZERO
	END IF
C
	RETURN
	END
