        MODULE MOD_VAR_MOM_J_CMF
	IMPLICIT NONE
!
	INTEGER VEC_LENGTH
	REAL*8, ALLOCATABLE :: TA(:)
	REAL*8, ALLOCATABLE :: TB(:)
	REAL*8, ALLOCATABLE :: TC(:)
	REAL*8, ALLOCATABLE :: DTAU(:)
	REAL*8, ALLOCATABLE :: RSQ_DTAUONQ(:)
	REAL*8, ALLOCATABLE :: XM(:)
	REAL*8, ALLOCATABLE :: SOURCE(:)
	REAL*8, ALLOCATABLE :: Q(:)
	REAL*8, ALLOCATABLE :: JNU(:)
	REAL*8, ALLOCATABLE :: RSQ_HNU(:)
	REAL*8, ALLOCATABLE :: VB(:)
	REAL*8, ALLOCATABLE :: VC(:)
	REAL*8, ALLOCATABLE :: HU(:)
	REAL*8, ALLOCATABLE :: HL(:)
	REAL*8, ALLOCATABLE :: HS(:)
	REAL*8, ALLOCATABLE :: GAM(:)
	REAL*8, ALLOCATABLE :: GAMH(:)
	REAL*8, ALLOCATABLE :: W(:)
	REAL*8, ALLOCATABLE :: WPREV(:)
	REAL*8, ALLOCATABLE :: PSI(:)
	REAL*8, ALLOCATABLE :: PSIPREV_MOD(:)
	REAL*8, ALLOCATABLE :: PSIPREV(:)
	REAL*8, ALLOCATABLE :: EPS_A(:)
	REAL*8, ALLOCATABLE :: EPS_B(:)
	REAL*8, ALLOCATABLE :: EPS_PREV_A(:)
	REAL*8, ALLOCATABLE :: EPS_PREV_B(:)
	REAL*8, ALLOCATABLE :: TX_OLD_d_T(:)
	REAL*8, ALLOCATABLE :: TX_OLD_d_dTdR(:)
	REAL*8, ALLOCATABLE :: JNUM1(:)
	REAL*8, ALLOCATABLE :: RSQ_HNUM1(:)
!
	END MODULE MOD_VAR_MOM_J_CMF
!
	SUBROUTINE MOD_VAR_MOM_ALLOC(ND)
	USE MOD_VAR_MOM_J_CMF
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER IOS
	INTEGER LUER
	INTEGER ERROR_LU
	EXTERNAL ERROR_LU
!
	ALLOCATE (TA(ND),TB(ND),TC(ND),DTAU(ND),RSQ_DTAUONQ(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (XM(ND),SOURCE(ND),Q(ND),JNU(ND),RSQ_HNU(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (VB(ND),VC(ND),HU(ND),HL(ND),HS(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (GAM(ND),GAMH(ND),W(ND),WPREV(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (PSI(ND),PSIPREV_MOD(ND),PSIPREV(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (EPS_A(ND),EPS_B(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (EPS_PREV_A(ND),EPS_PREV_B(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (TX_OLD_d_T(ND),TX_OLD_d_dTdR(ND),STAT=IOS)
	IF(IOS .EQ. 0)ALLOCATE (JNUM1(ND),RSQ_HNUM1(ND),STAT=IOS)
	VEC_LENGTH=ND
!
	IF(IOS .NE. 0)THEN
	  LUER=ERROR_LU()
	  WRITE(LUER,*)'Unable to allocate memory inf MOD_VAR_MOM_ALLOC'
	  WRITE(LUER,*)'STAT=',IOS
	  STOP
	END IF
!
	RETURN
	END	
