	SUBROUTINE SET_VERBOSE_INFO(VERBOSE)
	IMPLICIT NONE
	LOGICAL VERBOSE
	LOGICAL, SAVE :: VERBOSE_SETTING=.FALSE.
	VERBOSE_SETTING=VERBOSE
	RETURN
!
	ENTRY GET_VERBOSE_INFO(VERBOSE)
	VERBOSE=VERBOSE_SETTING
	RETURN
!
	END
