	SUBROUTINE GET_PGI_FILE_NUMBER(HARD_CNT,HARD_FILE)
	IMPLICIT NONE
	INTEGER HARD_CNT
	CHARACTER(LEN=*) HARD_FILE
!
	INTEGER I,L
!
	L=LEN_TRIM(HARD_FILE)
	DO I=L,1,-1
	  IF(INDEX(HARD_FILE(I:I),'.') .NE. 0)THEN
	     L=I-1
	     EXIT
	  END IF
	END DO
!
	DO I=L,1,-1
	  IF(HARD_FILE(I:I) .LT. '0' .OR. HARD_FILE(I:I) .GT. '9')THEN
	    IF(I .EQ. L)THEN
	      HARD_CNT=0
	      RETURN
	    ELSE
	      READ(HARD_FILE(I+1:L),*)HARD_CNT
	      RETURN
	    END IF
!
! Make sure not directory name
!
	  ELSE IF(HARD_FILE(I:I) .EQ. '/' .OR. HARD_FILE(I:I) .EQ. ']')THEN
	    HARD_CNT=0
	  END IF
	END DO
!
	RETURN
	END
!
	SUBROUTINE UPDATE_PGI_FILE_NAME(HARD_CNT,HARD_FILE)
	IMPLICIT NONE
	INTEGER HARD_CNT
	CHARACTER(LEN=*) HARD_FILE
!
	INTEGER I,L,K
	CHARACTER(LEN=20) TMP_STR,EXT
!
	K=LEN_TRIM(HARD_FILE); L=K
	DO I=K,1,-1
	  IF(INDEX(HARD_FILE(I:I),'.') .NE. 0)THEN
	     L=I-1
	     EXIT
	  END IF
	END DO
!
	EXT=' '
	IF(L .NE. K)EXT=HARD_FILE(L+1:K)
	IF(HARD_CNT .EQ. 0)THEN
	  HARD_FILE=HARD_FILE(1:L)//'_1'//EXT
	  HARD_CNT=1
	ELSE
	  HARD_CNT=HARD_CNT+1
	  DO I=L,1,-1
	    IF(HARD_FILE(I:I) .LT. '0' .OR. HARD_FILE(I:I) .GT. '9')THEN
	      HARD_FILE=HARD_FILE(1:I)
	      WRITE(TMP_STR,'(I5)')HARD_CNT
	      HARD_FILE=HARD_FILE(1:I)//TRIM(ADJUSTL(TMP_STR))//EXT
	      RETURN
	    END IF
	  END DO
	END IF
!
	RETURN
	END
