!
	FUNCTION MONINSIDE(X,XPAR)
	IMPLICIT NONE
!
! Altered 13-Feb-2001: Fixed to handle flipped axes.
! Modified 7-Jul-1999; Extract from MONBORD. Bug fixed.
!
	LOGICAL MONINSIDE
	REAL*4 X,XPAR(2),ACCURACY
	  MONINSIDE=.TRUE.
	  ACCURACY=(XPAR(2)-XPAR(1))*1.0E-04
	  IF(XPAR(1) .LT. XPAR(2))THEN
	    IF( X .LT. XPAR(1)-ACCURACY)MONINSIDE=.FALSE.
	    IF( X .GT. XPAR(2)+ACCURACY)MONINSIDE=.FALSE.
	  ELSE
	    IF( X .GT. XPAR(1)-ACCURACY)MONINSIDE=.FALSE.
	    IF( X .LT. XPAR(2)+ACCURACY)MONINSIDE=.FALSE.
	  END IF
	RETURN
	END
