	PROGRAM TST_PG
	IMPLICIT NONE
	INTEGER N,I,J,K
	PARAMETER (N=100)
	REAL*4 X(N),Y(N)
C
	DO K=1,2
	DO J=0,10
	DO I=1,N
	  X(I)=-1.5+4.0*I/100.0
	  Y(I)=(2.0*X(I))+J
	END DO
	CALL CURVE(N,X,Y)
	END DO
	CALL GRAMON_PGPLOT('X Axis','Y Axis','Lab 1',' ')
	END DO
	STOP
	END
