	FUNCTION CHK_LITTLE_ENDIAN()
	IMPLICIT NONE
	LOGICAL CHK_LITTLE_ENDIAN
	INTEGER(KIND=4) I
	INTEGER(KIND=1) HOPE(4)
!
	I=1
	CHK_LITTLE_ENDIAN=.FALSE.
	HOPE(1:4)=TRANSFER(I,HOPE)
	IF(HOPE(1) .EQ. 1)CHK_LITTLE_ENDIAN=.TRUE.
!
	RETURN
	END
