!       physical constants

	real*8, parameter :: c_kms=2.99792458d5            !km/s
	real*8, parameter :: jimpi=3.141592653589793d0
	real*8, parameter :: zero=0d0
	real*8, parameter :: one=1d0
	real*8, parameter :: two=2d0
	real*8, parameter :: onehalf=0.5d0
!
	integer, parameter :: izero=0
	integer, parameter :: ione=1
!
	logical, parameter :: true=.true.
	logical, parameter :: false=.false.
	logical, parameter :: forward=.true.
	logical, parameter :: backward=.false.
